version: '3'
services:
  autopilot-processor:
    image: autopilot-processor:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file:
      - api.env
    network_mode: "host"
